const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const {execFileSync}=require('node:child_process');const {selectChangeSpecs,detectDependencyChanges,crossesBreakingThreshold}=require('@isotope/changespec');
const root=path.resolve(__dirname,'..');
async function repo(t,baseFiles,headFiles){const d=await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(),'isotope-phase6-')));t.after(()=>fs.rm(d,{recursive:true,force:true}));execFileSync('git',['init','-q'],{cwd:d});execFileSync('git',['config','user.email','test@example.com'],{cwd:d});execFileSync('git',['config','user.name','test'],{cwd:d});for(const [f,v] of Object.entries(baseFiles)){await fs.mkdir(path.dirname(path.join(d,f)),{recursive:true});await fs.writeFile(path.join(d,f),v)}execFileSync('git',['add','.'],{cwd:d});execFileSync('git',['commit','-qm','base'],{cwd:d});const b=execFileSync('git',['rev-parse','HEAD'],{cwd:d}).toString().trim();for(const f of Object.keys(baseFiles))await fs.rm(path.join(d,f),{force:true});for(const [f,v] of Object.entries(headFiles)){await fs.mkdir(path.dirname(path.join(d,f)),{recursive:true});await fs.writeFile(path.join(d,f),v)}execFileSync('git',['add','-A'],{cwd:d});execFileSync('git',['commit','-qm','head'],{cwd:d});const h=execFileSync('git',['rev-parse','HEAD'],{cwd:d}).toString().trim();return {d,b,h}}
const specsRoot=path.join(root,'specs');
test('npm exact manifest crossing selects verified ChangeSpec and reports source',async t=>{const x=await repo(t,{'package.json':JSON.stringify({dependencies:{stripe:'17.7.0'}})},{'package.json':JSON.stringify({dependencies:{stripe:'18.1.0'}})});const r=await selectChangeSpecs({repositoryRoot:x.d,baseRef:x.b,headRef:x.h,specsRoot:specsRoot});assert.equal(r.selected.specs[0].id,'stripe.basil.subscription-period');assert.deepEqual(r.dependencyChanges[0],{ecosystem:'npm',package:'stripe',fromVersion:'17.7.0',toVersion:'18.1.0',sourceFiles:['package.json']})});
test('threshold boundaries, downgrade and already crossed do not match',()=>{const rule={ecosystem:'npm',packages:['stripe'],breaking_from:'18.0.0'};for(const [a,b,yes] of [['17.7.0','17.9.0',false],['17.7.0','18.0.0',true],['17.7.0','18.1.0',true],['18.0.0','18.1.0',false],['18.1.0','17.7.0',false]])assert.equal(crossesBreakingThreshold({ecosystem:'npm',package:'stripe',fromVersion:a,toVersion:b,sourceFiles:[]},rule.ecosystem,rule.packages,rule.breaking_from),yes)});
test('package-lock and pnpm lock resolved versions override ranges and dedupe evidence',async t=>{const x=await repo(t,{'package.json':JSON.stringify({dependencies:{stripe:'^17.0.0'}}),'package-lock.json':JSON.stringify({lockfileVersion:3,packages:{'':{dependencies:{stripe:'^17.0.0'}},'node_modules/stripe':{version:'17.7.0'}}})},{'package.json':JSON.stringify({dependencies:{stripe:'^18.0.0'}}),'package-lock.json':JSON.stringify({lockfileVersion:3,packages:{'':{dependencies:{stripe:'^18.0.0'}},'node_modules/stripe':{version:'18.0.0'}}})});const r=await selectChangeSpecs({repositoryRoot:x.d,baseRef:x.b,headRef:x.h,specsRoot:specsRoot});assert.deepEqual(r.dependencyChanges.map(c=>c.sourceFiles),[['package-lock.json']]);assert.equal(r.selected.specs.length,1)});
test('unrelated upgrade and unresolved ranges produce no selection and diagnostics',async t=>{const x=await repo(t,{'package.json':JSON.stringify({dependencies:{lodash:'^4.17.20',stripe:'^17.0.0'}})},{'package.json':JSON.stringify({dependencies:{lodash:'^4.17.21',stripe:'^18.0.0'}})});const r=await selectChangeSpecs({repositoryRoot:x.d,baseRef:x.b,headRef:x.h,specsRoot:specsRoot});assert.equal(r.selected.specs.length,0);assert.ok(r.diagnostics.some(x=>x.startsWith('unresolved-version:')))});
test('requirements exact pins use normalized PyPI identity and PEP boundary',async t=>{const x=await repo(t,{'requirements.txt':'Stripe==11.4.0\n'},{'requirements.txt':'stripe==12.0.0\n'});const r=await selectChangeSpecs({repositoryRoot:x.d,baseRef:x.b,headRef:x.h,specsRoot:specsRoot});assert.equal(r.dependencyChanges[0].package,'stripe');assert.equal(r.selected.specs.length,1)});
test('malformed committed spec is actionable while draft specs never enter selection',async t=>{const x=await repo(t,{'package.json':JSON.stringify({dependencies:{stripe:'17.7.0'}})},{'package.json':JSON.stringify({dependencies:{stripe:'18.0.0'}})});const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'isotope-specs-'));t.after(()=>fs.rm(tmp,{recursive:true,force:true}));await fs.mkdir(path.join(tmp,'stripe'));await fs.copyFile(path.join(specsRoot,'stripe/basil-subscription-period.yaml'),path.join(tmp,'stripe/human.yaml'));let text=await fs.readFile(path.join(tmp,'stripe/human.yaml'),'utf8');await fs.writeFile(path.join(tmp,'stripe/draft.yaml'),text.replace('verified_by: human','verified_by: draft').replace('verified_at: "2026-09-19"',''));const r=await selectChangeSpecs({repositoryRoot:x.d,baseRef:x.b,headRef:x.h,specsRoot:tmp});assert.equal(r.selected.specs.length,1);assert.ok(r.diagnostics.includes('unverified-spec:stripe.basil.subscription-period'))});
test('source-only changes have no dependency records',async t=>{const x=await repo(t,{'src/a.ts':'export const a=1'},{'src/a.ts':'export const a=2'});const r=await detectDependencyChanges({repositoryRoot:x.d,baseRef:x.b,headRef:x.h});assert.deepEqual(r.changes,[])});
