// The parser implementations are intentionally defensive and bounded; runtime validation occurs at the selection boundary.
// @ts-nocheck
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFile, readdir } from 'node:fs/promises';
import { join, relative, resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import { canonicalHash, validateContract, type ChangeSpec, type ChangeSpecEnvelope, type SelectedSpecs } from '@isotope/core';
import { lowerApprovedEnvelope } from './compiler/lower';
import { bindProject } from './compiler/bind-project';
const exec = promisify(execFile);
export interface DependencyChange { ecosystem: 'npm'|'pypi'; package: string; fromVersion: string; toVersion: string; sourceFiles: string[] }
export interface GitRevisionInput { repositoryRoot: string; baseRef: string; headRef: string }
export interface SelectionInput extends GitRevisionInput { specsRoot?: string }
export interface SelectionResult { dependencyChanges: DependencyChange[]; selected: SelectedSpecs; diagnostics: string[] }
export interface EnvelopeSelectionResult extends SelectionResult { envelope: ChangeSpecEnvelope; bundleHash: string }
const npmFiles = new Set(['package.json','pnpm-lock.yaml','package-lock.json']);
const pyFiles = new Set(['requirements.txt','pyproject.toml','poetry.lock']);
const normNpm=(s:string)=>s.trim();
const normPy=(s:string)=>s.trim().toLowerCase().replace(/[-_.]+/g,'-');
function semver(v:string): [number,number,number,string]|null { const m=v.trim().replace(/^v/,'').match(/^(\d+)\.(\d+)\.(\d+)(?:-([0-9A-Za-z.-]+))?/); return m?[+m[1],+m[2],+m[3],m[4]??'']:null; }
function cmpSemver(a:string,b:string):number { const x=semver(a),y=semver(b); if(!x||!y) return NaN; for(let i=0;i<3;i++) if(x[i]!==y[i]) return x[i]-y[i]; if(!x[3]&&!y[3])return 0;if(!x[3])return 1;if(!y[3])return -1;return x[3].localeCompare(y[3]); }
function pep(v:string): [number,number,number,string]|null { const m=v.trim().toLowerCase().replace(/^v/,'').match(/^(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:([a-z]+)(\d+)?)?/); return m?[+m[1],+(m[2]??0),+(m[3]??0),`${m[4]??''}${m[5]??''}`]:null; }
function cmpPep(a:string,b:string):number { const x=pep(a),y=pep(b); if(!x||!y)return NaN; for(let i=0;i<3;i++)if(x[i]!==y[i])return x[i]-y[i]; return x[3].localeCompare(y[3]); }
export function crossesBreakingThreshold(change:DependencyChange, ecosystem:string, packages:string[], threshold:string):boolean { if(change.ecosystem!==ecosystem || !packages.includes(change.package))return false; const cmp=ecosystem==='npm'?cmpSemver:cmpPep; return cmp(change.fromVersion,threshold)<0 && cmp(change.toVersion,threshold)>=0; }
async function git(root:string,args:string[]):Promise<string>{try{return (await exec('git',args,{cwd:root,maxBuffer:8*1024*1024})).stdout;}catch(e){throw new Error(`git ${args[0]} failed: ${(e as Error).message}`)}}
async function changedFiles(input:GitRevisionInput):Promise<string[]>{const out=await git(input.repositoryRoot,['diff','--name-status','-M',input.baseRef,input.headRef]);return out.split(/\r?\n/).filter(Boolean).flatMap(line=>{const p=line.split('\t');return p[0]?.startsWith('R')?p.slice(-1):[p[1]??p[0]??'']}).filter(Boolean).sort();}
async function blob(root:string,ref:string,file:string):Promise<string|null>{try{return await git(root,['show',`${ref}:${file}`])}catch{return null}}
function directManifest(text:string|null):Map<string,string>{const m=new Map<string,string>();if(!text)return m;try{const j=JSON.parse(text);for(const section of ['dependencies','devDependencies','optionalDependencies','peerDependencies'])for(const [k,v] of Object.entries(j[section]??{}))m.set(normNpm(k),String(v));}catch{}return m}
function exact(v:string):string|null{const x=v.trim().replace(/^['"]|['"]$/g,''); return /^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(x)?x:null}
function lockNpm(text:string|null):Map<string,string>{const m=new Map<string,string>();if(!text)return m;try{const j=JSON.parse(text);const walk=(o:any,name='')=>{if(!o||typeof o!=='object')return;if(typeof o.version==='string'&&name)m.set(normNpm(name),o.version);for(const [k,v] of Object.entries(o.dependencies??{}))walk(v,k)};walk(j);if(j.packages)for(const [k,v] of Object.entries(j.packages)){if(k.startsWith('node_modules/')){const n=k.slice(13);if((v as any).version)m.set(normNpm(n),(v as any).version)}}}catch{}return m}
function lockPnpm(text:string|null):Map<string,string>{const m=new Map<string,string>();if(!text)return m;const j=parseYaml(text) as any;for(const key of Object.keys(j?.snapshots??{})){const n=key.split('@')[0]||key;const match=key.match(/^(.*)@(\d+\.\d+\.\d+(?:-[^(/]+)?)/);if(match)m.set(normNpm(match[1]),match[2])}for(const key of Object.keys(j?.packages??{})){const match=key.match(/^\/(.*)@(\d+\.\d+\.\d+)/);if(match)m.set(normNpm(match[1]),match[2])}return m}
function reqPy(text:string|null):Map<string,string>{const m=new Map<string,string>();for(const line of (text??'').split(/\r?\n/)){const x=line.replace(/#.*$/,'').trim().match(/^([A-Za-z0-9_.-]+)\s*(===|==)\s*([0-9][^;\s]*)/);if(x)m.set(normPy(x[1]),x[3])}return m}
function pyproject(text:string|null):Map<string,string>{const m=new Map<string,string>();for(const line of (text??'').split(/\r?\n/)){const x=line.match(/^\s*["']?([A-Za-z0-9_.-]+)["']?\s*=\s*["'](\d+\.\d+\.\d+(?:[-+][^"']+)?)['"]/);if(x)m.set(normPy(x[1]),x[2]); const y=line.match(/["']([A-Za-z0-9_.-]+)\s*(?:==|===)\s*(\d+\.\d+\.\d+)/);if(y)m.set(normPy(y[1]),y[2])}return m}
function poetry(text:string|null):Map<string,string>{const m=new Map<string,string>();let name='';for(const line of (text??'').split(/\r?\n/)){const n=line.match(/^name\s*=\s*["']([^"']+)/);if(n)name=normPy(n[1]);const v=line.match(/^version\s*=\s*["'](\d+\.\d+\.\d+)/);if(v&&name)m.set(name,v[1])}return m}
async function allSpecs(root:string):Promise<ChangeSpec[]>{const files=(await readdir(root,{recursive:true})).filter(f=>/\.ya?ml$/.test(f)).sort();const out:ChangeSpec[]=[];for(const f of files){const parsed=parseYaml(await readFile(join(root,f),'utf8'));out.push(validateContract('ChangeSpec',parsed))}return out.sort((a,b)=>a.id.localeCompare(b.id));}
export async function detectDependencyChanges(input:GitRevisionInput):Promise<{changes:DependencyChange[]; diagnostics:string[]}>{const files=await changedFiles(input);const relevant=files.filter(f=>{const b=f.split('/').pop()!;return npmFiles.has(b)||pyFiles.has(b)});const diagnostics:string[]=[];const changes=new Map<string,DependencyChange>();
for(const file of relevant){const base=await blob(input.repositoryRoot,input.baseRef,file),head=await blob(input.repositoryRoot,input.headRef,file);const baseName=file.split('/').pop()!;const eco=npmFiles.has(baseName)?'npm':'pypi';let before:Map<string,string>,after:Map<string,string>;if(baseName==='package.json'){before=directManifest(base);after=directManifest(head)}else if(baseName==='package-lock.json'){before=lockNpm(base);after=lockNpm(head);const manifestBase=directManifest(await blob(input.repositoryRoot,input.baseRef,file.replace(/package-lock\.json$/,'package.json')));const manifestHead=directManifest(await blob(input.repositoryRoot,input.headRef,file.replace(/package-lock\.json$/,'package.json')));const direct=new Set([...manifestBase.keys(),...manifestHead.keys()]);before=new Map([...before].filter(([n])=>direct.has(n)));after=new Map([...after].filter(([n])=>direct.has(n)))}else if(baseName==='pnpm-lock.yaml'){before=lockPnpm(base);after=lockPnpm(head);const manifestBase=directManifest(await blob(input.repositoryRoot,input.baseRef,file.replace(/pnpm-lock\.yaml$/,'package.json')));const manifestHead=directManifest(await blob(input.repositoryRoot,input.headRef,file.replace(/pnpm-lock\.yaml$/,'package.json')));const direct=new Set([...manifestBase.keys(),...manifestHead.keys()]);before=new Map([...before].filter(([n])=>direct.has(n)));after=new Map([...after].filter(([n])=>direct.has(n)))}else if(baseName==='requirements.txt'){before=reqPy(base);after=reqPy(head)}else if(baseName==='pyproject.toml'){before=pyproject(base);after=pyproject(head)}else {before=poetry(base);after=poetry(head)};const names=new Set([...before.keys(),...after.keys()]);for(const pkg of [...names].sort()){const a=before.get(pkg),b=after.get(pkg);const av=exact(a??''),bv=exact(b??'');if(!av||!bv){if(a!==b)diagnostics.push(`unresolved-version:${file}:${pkg}`);continue}if(av===bv)continue;const key=`${eco}:${pkg}:${av}:${bv}`;const prior=changes.get(key);changes.set(key,{ecosystem:eco,package:pkg,fromVersion:av,toVersion:bv,sourceFiles:[...(prior?.sourceFiles??[]),file]})}}
return {changes:[...changes.values()].map(c=>({...c,sourceFiles:[...new Set(c.sourceFiles)].sort()})).sort((a,b)=>`${a.ecosystem}:${a.package}:${a.fromVersion}:${a.toVersion}`.localeCompare(`${b.ecosystem}:${b.package}:${b.fromVersion}:${b.toVersion}`)),diagnostics:[...new Set(diagnostics)].sort()}}
export async function selectChangeSpecs(input:SelectionInput):Promise<SelectionResult>{const detected=await detectDependencyChanges(input);const specs=await allSpecs(input.specsRoot??join(input.repositoryRoot,'specs'));const selected:ChangeSpec[]=[];const selectedChanges:any[]=[];for(const change of detected.changes){for(const spec of specs){for(const [eco,rule] of Object.entries(spec.detection.ecosystems)){if(!crossesBreakingThreshold(change,eco,(rule as any).packages,(rule as any).breaking_from))continue;if(spec.verified_by!=='human'){detected.diagnostics.push(`unverified-spec:${spec.id}`);continue}if(!selected.some(x=>x.id===spec.id)){selected.push(spec);selectedChanges.push({ecosystem:change.ecosystem,package:change.package,from_version:change.fromVersion,to_version:change.toVersion})}}}}const selectedArtifact=validateContract('SelectedSpecs',{schemaVersion:1,dependencyChanges:selectedChanges.sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b))),specs:selected.sort((a,b)=>a.id.localeCompare(b.id))});return {dependencyChanges:detected.changes,selected:selectedArtifact,diagnostics:[...new Set(detected.diagnostics)].sort()}}

export async function selectApprovedEnvelope(input: GitRevisionInput & { bundlePath: string }): Promise<EnvelopeSelectionResult> {
  const detected = await detectDependencyChanges(input);
  const envelope = validateContract('ChangeSpecEnvelope', JSON.parse(await readFile(resolve(input.bundlePath), 'utf8')) as unknown);
  if (envelope.status !== 'approved') throw new Error(`ChangeSpec envelope is not approved: ${envelope.status}`);
  const binding = envelope.dependencyBinding;
  const matches = detected.changes.filter(change => change.ecosystem === binding.ecosystem && change.package === binding.package && change.fromVersion === binding.fromVersion && change.toVersion === binding.toVersion);
  if (matches.length !== 1) throw new Error(`Approved envelope requires exactly one detected transition ${binding.ecosystem}:${binding.package}:${binding.fromVersion}->${binding.toVersion}; found ${matches.length}`);
  const currentProjectBinding = await bindProject(envelope.candidate, binding, input.repositoryRoot);
  if (currentProjectBinding.status !== 'bound' || canonicalHash(currentProjectBinding) !== canonicalHash(envelope.projectBinding)) throw new Error('Approved envelope project binding does not match the current repository');
  const runtime = lowerApprovedEnvelope(envelope);
  const change = matches[0]!;
  const selected = validateContract('SelectedSpecs', { schemaVersion: 1, dependencyChanges: [{ ecosystem: change.ecosystem, package: change.package, from_version: change.fromVersion, to_version: change.toVersion }], specs: [runtime] });
  return { dependencyChanges: detected.changes, selected, diagnostics: detected.diagnostics, envelope, bundleHash: envelope.bundleHash };
}
